version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "5179:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017  # Указываем на сервис MongoDB
    ports:
      - "8099:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
