version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "5179:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
    working_dir: /app/backend
    environment:
      - PYTHONPATH=/app
    ports:
      - "8099:8000"
    volumes:
      - ../.:/app